name: Sync Fork with Upstream

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          # Replace the URL below with your upstream repository URL
          git remote add upstream https://github.com/nvim-orgmode/orgmode.git

      - name: Fetch upstream
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          # Check which branch we're on
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Remove tests.yml before merging to avoid the specific conflict we don't care about
          if [ -f .github/workflows/tests.yml ]; then
            git rm .github/workflows/tests.yml
            git commit -m "Remove tests.yml before upstream merge"
          fi

          # Attempt to merge upstream changes
          if ! git merge upstream/$CURRENT_BRANCH --no-edit; then
            echo "Merge conflicts detected"
            
            # Get all conflicted files
            CONFLICT_FILES=$(git diff --name-only --diff-filter=U)
            
            # Filter out tests.yml conflicts that we want to auto-resolve
            OTHER_CONFLICTS=""
            for file in $CONFLICT_FILES; do
              if [[ "$file" != ".github/workflows/tests.yml" ]]; then
                OTHER_CONFLICTS="$OTHER_CONFLICTS $file"
              fi
            done
            
            # If there are conflicts other than tests.yml, fail
            if [ -n "$OTHER_CONFLICTS" ]; then
              echo "Unresolved conflicts in files other than tests.yml:"
              echo "$OTHER_CONFLICTS"
              echo "These conflicts require manual review. Failing the workflow."
              exit 1
            fi
            
            # Only tests.yml conflict remains - resolve it by keeping it deleted
            if echo "$CONFLICT_FILES" | grep -q ".github/workflows/tests.yml"; then
              echo "Resolving tests.yml conflict by keeping it deleted"
              git rm .github/workflows/tests.yml || true
            fi
            
            # Complete the merge
            git commit --no-edit
          fi
