name: Sync Fork with Upstream

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          # Replace the URL below with your upstream repository URL
          git remote add upstream https://github.com/nvim-orgmode/orgmode.git

      - name: Fetch upstream
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          # Check which branch we're on
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Sync the current branch with upstream
          git merge upstream/$CURRENT_BRANCH --no-edit
          j
      - name: Set up GitHub CLI
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Push with GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_TOKEN }}" | gh auth login --with-token
          git push origin HEAD:master
